@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "org.apache.nifi.logging.ComponentLog#info(String,Throwable)",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": ""
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false // root node is included
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "org.apache.nifi.logging.ComponentLog"
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_1411517106 { 
   	label=apache
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_781648802 { 
   	label=nifi
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1250929481 { 
   	label=SimpleProcessLogger
	labeljust=l
	fillcolor=white
	style=filled
   
   SimpleProcessLogger786985848XXXdebug424332965[
	label="+ debug()"
	style=filled
	fillcolor=white
	tooltip="SimpleProcessLogger

null"
	fontcolor=darkgreen
];

SimpleProcessLogger786985848XXXinfo424332965[
	label="+ info()"
	style=filled
	fillcolor=white
	tooltip="SimpleProcessLogger

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1534396166 { 
   	label=NopComponentLog
	labeljust=l
	fillcolor=white
	style=filled
   
   NopComponentLog832281502XXXdebug424332965[
	label="+ debug()"
	style=filled
	fillcolor=white
	tooltip="NopComponentLog

null"
	fontcolor=darkgreen
];

NopComponentLog832281502XXXinfo424332965[
	label="+ info()"
	style=filled
	fillcolor=white
	tooltip="NopComponentLog

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1684153142 { 
   	label=StandardLogRepository
	labeljust=l
	fillcolor=white
	style=filled
   
   StandardLogRepository1292167443XXXaddLogMessage1690274905[
	label="+ addLogMessage()"
	style=filled
	fillcolor=white
	tooltip="StandardLogRepository

null"
	fontcolor=darkgreen
];

StandardLogRepository1292167443XXXaddLogMessage936633774[
	label="+ addLogMessage()"
	style=filled
	fillcolor=white
	tooltip="StandardLogRepository

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1708012223 { 
   	label=CapturingLogger
	labeljust=l
	fillcolor=white
	style=filled
   
   CapturingLogger306090332XXXdebug1506910935[
	label="+ debug()"
	style=filled
	fillcolor=white
	tooltip="CapturingLogger

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1921211216 { 
   	label=ComponentLog
	labeljust=l
	fillcolor=white
	style=filled
   
   ComponentLog978875333XXXinfo424332965[
	label="+ info()"
	style=filled
	fillcolor=white
	tooltip="ComponentLog

null"
	penwidth=4
	fontcolor=darkgreen
];
} 

subgraph cluster_2048858659 { 
   	label=MockComponentLog
	labeljust=l
	fillcolor=white
	style=filled
   
   MockComponentLog306090332XXXdebug424332965[
	label="+ debug()"
	style=filled
	fillcolor=white
	tooltip="MockComponentLog

null"
	fontcolor=darkgreen
];

MockComponentLog306090332XXXinfo424332965[
	label="+ info()"
	style=filled
	fillcolor=white
	tooltip="MockComponentLog

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_2062646041 { 
   	label=PutAccumuloRecord
	labeljust=l
	fillcolor=white
	style=filled
   
   PutAccumuloRecord1352152982XXXonScheduled135384992[
	label="+ onScheduled()"
	style=filled
	fillcolor=white
	tooltip="PutAccumuloRecord

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_219057026 { 
   	label=TerminationAwareLogger
	labeljust=l
	fillcolor=white
	style=filled
   
   TerminationAwareLogger1158014602XXXdebug424332965[
	label="+ debug()"
	style=filled
	fillcolor=white
	tooltip="TerminationAwareLogger

null"
	fontcolor=darkgreen
];

TerminationAwareLogger1158014602XXXinfo424332965[
	label="+ info()"
	style=filled
	fillcolor=white
	tooltip="TerminationAwareLogger

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_492547111 { 
   	label=MockComponentLogger
	labeljust=l
	fillcolor=white
	style=filled
   
   MockComponentLogger305847012XXXdebug424332965[
	label="+ debug()"
	style=filled
	fillcolor=white
	tooltip="MockComponentLogger

null"
	fontcolor=darkgreen
];

MockComponentLogger305847012XXXinfo424332965[
	label="+ info()"
	style=filled
	fillcolor=white
	tooltip="MockComponentLogger

null"
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
ComponentLog978875333XXXinfo424332965 -> MockComponentLog306090332XXXinfo424332965;
ComponentLog978875333XXXinfo424332965 -> MockComponentLogger305847012XXXinfo424332965;
ComponentLog978875333XXXinfo424332965 -> NopComponentLog832281502XXXinfo424332965;
ComponentLog978875333XXXinfo424332965 -> SimpleProcessLogger786985848XXXinfo424332965;
ComponentLog978875333XXXinfo424332965 -> TerminationAwareLogger1158014602XXXinfo424332965;
MockComponentLog306090332XXXdebug424332965 -> CapturingLogger306090332XXXdebug1506910935;
PutAccumuloRecord1352152982XXXonScheduled135384992 -> ComponentLog978875333XXXinfo424332965;
SimpleProcessLogger786985848XXXinfo424332965 -> StandardLogRepository1292167443XXXaddLogMessage936633774;
StandardLogRepository1292167443XXXaddLogMessage936633774 -> StandardLogRepository1292167443XXXaddLogMessage1690274905;
TerminationAwareLogger1158014602XXXinfo424332965 -> ComponentLog978875333XXXinfo424332965;
TerminationAwareLogger1158014602XXXinfo424332965 -> MockComponentLog306090332XXXdebug424332965;
TerminationAwareLogger1158014602XXXinfo424332965 -> MockComponentLogger305847012XXXdebug424332965;
TerminationAwareLogger1158014602XXXinfo424332965 -> NopComponentLog832281502XXXdebug424332965;
TerminationAwareLogger1158014602XXXinfo424332965 -> SimpleProcessLogger786985848XXXdebug424332965;
TerminationAwareLogger1158014602XXXinfo424332965 -> TerminationAwareLogger1158014602XXXdebug424332965;
    
}
@enduml