apiVersion: v1
kind: Service
metadata:
  name: aks-registry
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 18080
  selector:
    app.kubernetes.io/instance: nifi
    app.kubernetes.io/name: registry 
  publishNotReadyAddresses: true
