apiVersion: v1
kind: Service
metadata:
  name: aks-prometheus
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  namespace: monitoring
spec:
  type: LoadBalancer
  ports:
  - port: 9090
  selector:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: k8s
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: kube-prometheus
  publishNotReadyAddresses: true
