apiVersion: v1
kind: Service
metadata:
  name: aks-hazelcast
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 8888
    targetPort: 8080 
  selector:
    app.kubernetes.io/instance: hazelcast
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: hazelcast-mancenter
  publishNotReadyAddresses: true
