apiVersion: v1
kind: Service
metadata:
  name: aks-nifi 
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
    - name: gui
      port: 8080
    - name: liveschedule
      port: 8000
    - name: liveschedulechoices
      port: 8001
  selector:
    app: nifi
  publishNotReadyAddresses: true
