apiVersion: v1
kind: Service
metadata:
  name: hazelcast-service 
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: hazelcast
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: hazelcast
  ports:
  - name: hazelcast
    port: 5701
  publishNotReadyAddresses: true
