apiVersion: v1
kind: Service
metadata:
  name: aks-nifi 
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: nifi
  publishNotReadyAddresses: true
